title: Taiga Ð¡orpus
description: An open-source corpus for machine learning.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
baseurl: /taiga-corpus-website

# files excluded from Jekyll builds
exclude:
- README.md
- CNAME
- LICENSE
- Gemfile
- Gemfile.lock

# site settings
encoding: utf-8
lang: en-GB
